### ISSUE TITLE
"error in deps" could be more detailed

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#291] opened 2020-08-02 10:31 UTC
when the module, that acts as a dependency for some other module is removed, then the status of the dependent modules change to "error in deps". the proposal is to show also what kind of module is missing (like O1 or Robots)

**Comment by OlliKiljunen** [comment] 2020-10-09 08:28
Related to (and possible duplicate of) #387

**Closed** 2021-01-08 13:36 UTC
Labels: low
