### ISSUE TITLE
installed modules can recover from removal of the module they depend on (O1)

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#367] opened 2020-09-01 13:09 UTC
maybe keeping a list of dependencies elsewhere than .iml file delivered (as it's subject to change by the IDE)

**Comment by superseacat** [comment] 2020-09-01 13:12
IntelliJ project model (wo modification of the iml's directly)

**Comment by OlliKiljunen** [comment] 2020-10-09 07:43
Duplicate of #387

**Closed by OlliKiljunen** 2020-10-09 07:43 UTC
Labels: questionable
